#! /bin/env python3

import requests
import mechanize
from bs4 import BeautifulSoup
import sys

import http.cookiejar

def format_bytes(size):
    # 2**10 = 1024
    power = 2**10
    n = 0
    power_labels = {0 : '', 1: 'K', 2: 'M', 3: 'G', 4: 'T'}
    while size > power:
        size /= power
        n += 1
    return f"{size:.2f} {power_labels[n]}B"

def scrape(username, password):
    cookies = http.cookiejar.CookieJar()
    browser = mechanize.Browser()
    browser.set_cookiejar(cookies)
    browser.open('https://netz.studiwerk.de/login')

    browser.select_form(nr=0)

    browser.form['_username'] = username
    browser.form['_password'] = password
    browser.submit()

    # sessionid = cookies._cookies['netz.studiwerk.de']['/']['PHPSESSID'].value

    browser.open('https://netz.studiwerk.de/')

    content = browser.response().read()

    soup = BeautifulSoup(content, 'html.parser')
    trafficLimit = soup.find('strong', {'id': 'trafficlimit'}).text.split(' ')[0]
    totalTraffic = soup.find('strong', {'id': 'totaltraffic'}).text.split(' ')[0]
    used = format_bytes(int(totalTraffic))
    limit = format_bytes(int(trafficLimit))

    return f"{used} / {limit}"

if __name__ == '__main__':
    username = sys.argv[1]
    password = sys.argv[2]
    print(scrape(username, password))